[   {   'boot_files': {   },
        'comment': '',
        'ctime': 1458531424.986043,
        'depth': 2,
        'enable_gpxe': 0,
        'fetchable_files': {   },
        'gateway': '10.33.33.1',
        'hostname': 'infra01.rs.zbi.cba',
        'image': '',
        'interfaces': {   'em1': {   'bonding': '',
                                     'bonding_master': '',
                                     'bonding_opts': '',
                                     'bridge_opts': '',
                                     'cnames': [],
                                     'dhcp_tag': '',
                                     'distro': {   'arch': 'x86_64',
                                                   'boot_files': {   },
                                                   'breed': 'ubuntu',
                                                   'comment': '',
                                                   'ctime': 1447693852.378105,
                                                   'depth': 0,
                                                   'fetchable_files': {   },
                                                   'initrd': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/initrd.gz',
                                                   'kernel': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/linux',
                                                   'kernel_options': {   },
                                                   'kernel_options_post': {   },
                                                   'ks_meta': {   'tree': 'http://@@http_server@@/cblr/links/ubuntu-14.04.3-server-x86_64'},
                                                   'mgmt_classes': [],
                                                   'mtime': 1447693853.425006,
                                                   'name': 'ubuntu-14.04.3-server-x86_64',
                                                   'os_version': 'trusty',
                                                   'owners': ['admin'],
                                                   'redhat_management_key': '<<inherit>>',
                                                   'redhat_management_server': '<<inherit>>',
                                                   'source_repos': [],
                                                   'template_files': {   },
                                                   'tree_build_time': 0,
                                                   'uid': 'MTQ0NzY5Mzg1Mi4zODY4NDc3Ny43MTk2NTk'},
                                     'dns_name': '',
                                     'enable_gpxe': 0,
                                     'filename': '/pxelinux.0',
                                     'gateway': '10.33.33.1',
                                     'hostname': 'infra01.rs.zbi.cba',
                                     'if_gateway': '',
                                     'interface_master': '',
                                     'interface_type': '',
                                     'ip_address': '10.33.33.50',
                                     'ipv6_address': '',
                                     'ipv6_default_gateway': '',
                                     'ipv6_mtu': '',
                                     'ipv6_secondaries': [],
                                     'ipv6_static_routes': [],
                                     'mac_address': '0c:c4:7a:a9:0a:52',
                                     'management': False,
                                     'mtu': '',
                                     'name': 'generic1',
                                     'netboot_enabled': True,
                                     'netmask': '255.255.255.0',
                                     'next_server': '10.33.33.2',
                                     'owner': 'infra01.rs.zbi.cba',
                                     'static': False,
                                     'static_routes': [],
                                     'subnet': '',
                                     'virt_bridge': ''}},
        'ipv6_autoconfiguration': False,
        'ipv6_default_device': '',
        'kernel_options': {   'interface': 'em1'},
        'kernel_options_post': {   },
        'kickstart': '<<inherit>>',
        'ks_meta': { 'CONTROL_PLANE': 'A' },
        'ldap_enabled': False,
        'ldap_type': 'authconfig',
        'mgmt_classes': [],
        'mgmt_parameters': '<<inherit>>',
        'monit_enabled': False,
        'mtime': 1458532202.664248,
        'name': 'infra01.rs.zbi.cba',
        'name_servers': ['10.33.33.1'],
        'name_servers_search': [],
        'netboot_enabled': False,
        'owners': ['admin'],
        'power_address': '10.44.44.101',
        'power_id': '',
        'power_pass': 'ADMIN',
        'power_type': 'ipmilan',
        'power_user': 'ADMIN',
        'profile': 'ubuntu-14.04.3-server-unattended-rpc',
        'proxy': '<<inherit>>',
        'redhat_management_key': '<<inherit>>',
        'redhat_management_server': '<<inherit>>',
        'repos_enabled': False,
        'server': '<<inherit>>',
        'status': 'production',
        'template_files': {   },
        'template_remote_kickstarts': 0,
        'uid': 'MTQ1ODUzMTQyNC45OTg5NzM3MzYuODc3NzQ',
        'virt_auto_boot': '<<inherit>>',
        'virt_cpus': '<<inherit>>',
        'virt_disk_driver': '<<inherit>>',
        'virt_file_size': '<<inherit>>',
        'virt_path': '<<inherit>>',
        'virt_pxe_boot': 0,
        'virt_ram': '<<inherit>>',
        'virt_type': '<<inherit>>'},
    {   'boot_files': {   },
        'comment': '',
        'ctime': 1458531425.602924,
        'depth': 2,
        'enable_gpxe': 0,
        'fetchable_files': {   },
        'gateway': '10.33.33.1',
        'hostname': 'infra02.rs.zbi.cba',
        'image': '',
        'interfaces': {   'em1': {   'bonding': '',
                                     'bonding_master': '',
                                     'bonding_opts': '',
                                     'bridge_opts': '',
                                     'cnames': [],
                                     'dhcp_tag': '',
                                     'distro': {   'arch': 'x86_64',
                                                   'boot_files': {   },
                                                   'breed': 'ubuntu',
                                                   'comment': '',
                                                   'ctime': 1447693852.378105,
                                                   'depth': 0,
                                                   'fetchable_files': {   },
                                                   'initrd': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/initrd.gz',
                                                   'kernel': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/linux',
                                                   'kernel_options': {   },
                                                   'kernel_options_post': {   },
                                                   'ks_meta': {   'tree': 'http://@@http_server@@/cblr/links/ubuntu-14.04.3-server-x86_64'},
                                                   'mgmt_classes': [],
                                                   'mtime': 1447693853.425006,
                                                   'name': 'ubuntu-14.04.3-server-x86_64',
                                                   'os_version': 'trusty',
                                                   'owners': ['admin'],
                                                   'redhat_management_key': '<<inherit>>',
                                                   'redhat_management_server': '<<inherit>>',
                                                   'source_repos': [],
                                                   'template_files': {   },
                                                   'tree_build_time': 0,
                                                   'uid': 'MTQ0NzY5Mzg1Mi4zODY4NDc3Ny43MTk2NTk'},
                                     'dns_name': '',
                                     'enable_gpxe': 0,
                                     'filename': '/pxelinux.0',
                                     'gateway': '10.33.33.1',
                                     'hostname': 'infra02.rs.zbi.cba',
                                     'if_gateway': '',
                                     'interface_master': '',
                                     'interface_type': '',
                                     'ip_address': '10.33.33.51',
                                     'ipv6_address': '',
                                     'ipv6_default_gateway': '',
                                     'ipv6_mtu': '',
                                     'ipv6_secondaries': [],
                                     'ipv6_static_routes': [],
                                     'mac_address': '0c:c4:7a:6c:b3:5a',
                                     'management': False,
                                     'mtu': '',
                                     'name': 'generic2',
                                     'netboot_enabled': True,
                                     'netmask': '255.255.255.0',
                                     'next_server': '10.33.33.2',
                                     'owner': 'infra02.rs.zbi.cba',
                                     'static': False,
                                     'static_routes': [],
                                     'subnet': '',
                                     'virt_bridge': ''}},
        'ipv6_autoconfiguration': False,
        'ipv6_default_device': '',
        'kernel_options': {   'interface': 'em1'},
        'kernel_options_post': {   },
        'kickstart': '<<inherit>>',
        'ks_meta': {   },
        'ldap_enabled': False,
        'ldap_type': 'authconfig',
        'mgmt_classes': [],
        'mgmt_parameters': '<<inherit>>',
        'monit_enabled': False,
        'mtime': 1458532220.809102,
        'name': 'infra02.rs.zbi.cba',
        'name_servers': ['10.33.33.1'],
        'name_servers_search': [],
        'netboot_enabled': False,
        'owners': ['admin'],
        'power_address': '10.44.44.103',
        'power_id': '',
        'power_pass': 'ADMIN',
        'power_type': 'ipmilan',
        'power_user': 'ADMIN',
        'profile': 'ubuntu-14.04.3-server-unattended-rpc',
        'proxy': '<<inherit>>',
        'redhat_management_key': '<<inherit>>',
        'redhat_management_server': '<<inherit>>',
        'repos_enabled': False,
        'server': '<<inherit>>',
        'status': 'production',
        'template_files': {   },
        'template_remote_kickstarts': 0,
        'uid': 'MTQ1ODUzMTQyNS42NTgyNzMwMy4xMDc1Nw',
        'virt_auto_boot': '<<inherit>>',
        'virt_cpus': '<<inherit>>',
        'virt_disk_driver': '<<inherit>>',
        'virt_file_size': '<<inherit>>',
        'virt_path': '<<inherit>>',
        'virt_pxe_boot': 0,
        'virt_ram': '<<inherit>>',
        'virt_type': '<<inherit>>'},
    {   'boot_files': {   },
        'comment': '',
        'ctime': 1458535220.841753,
        'depth': 2,
        'enable_gpxe': 0,
        'fetchable_files': {   },
        'gateway': '10.33.33.1',
        'hostname': 'logging01.rs.zbi.cba',
        'image': '',
        'interfaces': {   'em2': {   'bonding': '',
                                     'bonding_master': '',
                                     'bonding_opts': '',
                                     'bridge_opts': '',
                                     'cnames': [],
                                     'dhcp_tag': '',
                                     'distro': {   'arch': 'x86_64',
                                                   'boot_files': {   },
                                                   'breed': 'ubuntu',
                                                   'comment': '',
                                                   'ctime': 1447693852.378105,
                                                   'depth': 0,
                                                   'fetchable_files': {   },
                                                   'initrd': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/initrd.gz',
                                                   'kernel': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/linux',
                                                   'kernel_options': {   },
                                                   'kernel_options_post': {   },
                                                   'ks_meta': {   'tree': 'http://@@http_server@@/cblr/links/ubuntu-14.04.3-server-x86_64'},
                                                   'mgmt_classes': [],
                                                   'mtime': 1447693853.425006,
                                                   'name': 'ubuntu-14.04.3-server-x86_64',
                                                   'os_version': 'trusty',
                                                   'owners': ['admin'],
                                                   'redhat_management_key': '<<inherit>>',
                                                   'redhat_management_server': '<<inherit>>',
                                                   'source_repos': [],
                                                   'template_files': {   },
                                                   'tree_build_time': 0,
                                                   'uid': 'MTQ0NzY5Mzg1Mi4zODY4NDc3Ny43MTk2NTk'},
                                     'dns_name': '',
                                     'enable_gpxe': 0,
                                     'filename': '/pxelinux.0',
                                     'gateway': '10.33.33.1',
                                     'hostname': 'logging01.rs.zbi.cba',
                                     'if_gateway': '',
                                     'interface_master': '',
                                     'interface_type': '',
                                     'ip_address': '10.33.33.55',
                                     'ipv6_address': '',
                                     'ipv6_default_gateway': '',
                                     'ipv6_mtu': '',
                                     'ipv6_secondaries': [],
                                     'ipv6_static_routes': [],
                                     'mac_address': '0c:c4:7a:c1:2d:71',
                                     'management': False,
                                     'mtu': '',
                                     'name': 'generic3',
                                     'netboot_enabled': True,
                                     'netmask': '255.255.255.0',
                                     'next_server': '10.33.33.2',
                                     'owner': 'logging01.rs.zbi.cba',
                                     'static': False,
                                     'static_routes': [],
                                     'subnet': '',
                                     'virt_bridge': ''}},
        'ipv6_autoconfiguration': False,
        'ipv6_default_device': '',
        'kernel_options': {   'interface': 'em2'},
        'kernel_options_post': {   },
        'kickstart': '<<inherit>>',
        'ks_meta': {   },
        'ldap_enabled': False,
        'ldap_type': 'authconfig',
        'mgmt_classes': [],
        'mgmt_parameters': '<<inherit>>',
        'monit_enabled': False,
        'mtime': 1458535766.107188,
        'name': 'logging01.rs.zbi.cba',
        'name_servers': ['10.33.33.1'],
        'name_servers_search': [],
        'netboot_enabled': False,
        'owners': ['admin'],
        'power_address': '10.44.44.106',
        'power_id': '',
        'power_pass': 'ADMIN',
        'power_type': 'ipmilan',
        'power_user': 'ADMIN',
        'profile': 'ubuntu-14.04.3-server-unattended-rpc',
        'proxy': '<<inherit>>',
        'redhat_management_key': '<<inherit>>',
        'redhat_management_server': '<<inherit>>',
        'repos_enabled': False,
        'server': '<<inherit>>',
        'status': 'production',
        'template_files': {   },
        'template_remote_kickstarts': 0,
        'uid': 'MTQ1ODUzNTIyMC44NDY0MjkwMjUuNDYyMQ',
        'virt_auto_boot': '<<inherit>>',
        'virt_cpus': '<<inherit>>',
        'virt_disk_driver': '<<inherit>>',
        'virt_file_size': '<<inherit>>',
        'virt_path': '<<inherit>>',
        'virt_pxe_boot': 0,
        'virt_ram': '<<inherit>>',
        'virt_type': '<<inherit>>'},
    {   'boot_files': {   },
        'comment': '',
        'ctime': 1458531425.88283,
        'depth': 2,
        'enable_gpxe': 0,
        'fetchable_files': {   },
        'gateway': '10.33.33.1',
        'hostname': 'infra03.rs.zbi.cba',
        'image': '',
        'interfaces': {   'em1': {   'bonding': '',
                                     'bonding_master': '',
                                     'bonding_opts': '',
                                     'bridge_opts': '',
                                     'cnames': [],
                                     'dhcp_tag': '',
                                     'distro': {   'arch': 'x86_64',
                                                   'boot_files': {   },
                                                   'breed': 'ubuntu',
                                                   'comment': '',
                                                   'ctime': 1447693852.378105,
                                                   'depth': 0,
                                                   'fetchable_files': {   },
                                                   'initrd': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/initrd.gz',
                                                   'kernel': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/linux',
                                                   'kernel_options': {   },
                                                   'kernel_options_post': {   },
                                                   'ks_meta': {   'tree': 'http://@@http_server@@/cblr/links/ubuntu-14.04.3-server-x86_64'},
                                                   'mgmt_classes': [],
                                                   'mtime': 1447693853.425006,
                                                   'name': 'ubuntu-14.04.3-server-x86_64',
                                                   'os_version': 'trusty',
                                                   'owners': ['admin'],
                                                   'redhat_management_key': '<<inherit>>',
                                                   'redhat_management_server': '<<inherit>>',
                                                   'source_repos': [],
                                                   'template_files': {   },
                                                   'tree_build_time': 0,
                                                   'uid': 'MTQ0NzY5Mzg1Mi4zODY4NDc3Ny43MTk2NTk'},
                                     'dns_name': '',
                                     'enable_gpxe': 0,
                                     'filename': '/pxelinux.0',
                                     'gateway': '10.33.33.1',
                                     'hostname': 'infra03.rs.zbi.cba',
                                     'if_gateway': '',
                                     'interface_master': '',
                                     'interface_type': '',
                                     'ip_address': '10.33.33.52',
                                     'ipv6_address': '',
                                     'ipv6_default_gateway': '',
                                     'ipv6_mtu': '',
                                     'ipv6_secondaries': [],
                                     'ipv6_static_routes': [],
                                     'mac_address': '0c:c4:7a:a8:89:d6',
                                     'management': False,
                                     'mtu': '',
                                     'name': 'generic3',
                                     'netboot_enabled': True,
                                     'netmask': '255.255.255.0',
                                     'next_server': '10.33.33.2',
                                     'owner': 'infra03.rs.zbi.cba',
                                     'static': False,
                                     'static_routes': [],
                                     'subnet': '',
                                     'virt_bridge': ''}},
        'ipv6_autoconfiguration': False,
        'ipv6_default_device': '',
        'kernel_options': {   'interface': 'em1'},
        'kernel_options_post': {   },
        'kickstart': '<<inherit>>',
        'ks_meta': {   },
        'ldap_enabled': False,
        'ldap_type': 'authconfig',
        'mgmt_classes': [],
        'mgmt_parameters': '<<inherit>>',
        'monit_enabled': False,
        'mtime': 1458532702.125739,
        'name': 'infra03.rs.zbi.cba',
        'name_servers': ['10.33.33.1'],
        'name_servers_search': [],
        'netboot_enabled': False,
        'owners': ['admin'],
        'power_address': '10.44.44.104',
        'power_id': '',
        'power_pass': 'ADMIN',
        'power_type': 'ipmilan',
        'power_user': 'ADMIN',
        'profile': 'ubuntu-14.04.3-server-unattended-rpc',
        'proxy': '<<inherit>>',
        'redhat_management_key': '<<inherit>>',
        'redhat_management_server': '<<inherit>>',
        'repos_enabled': False,
        'server': '<<inherit>>',
        'status': 'production',
        'template_files': {   },
        'template_remote_kickstarts': 0,
        'uid': 'MTQ1ODUzMTQyNS44ODk3MTQyMS45Mjg0ODU',
        'virt_auto_boot': '<<inherit>>',
        'virt_cpus': '<<inherit>>',
        'virt_disk_driver': '<<inherit>>',
        'virt_file_size': '<<inherit>>',
        'virt_path': '<<inherit>>',
        'virt_pxe_boot': 0,
        'virt_ram': '<<inherit>>',
        'virt_type': '<<inherit>>'},
    {   'boot_files': {   },
        'comment': '',
        'ctime': 1458535221.153445,
        'depth': 2,
        'enable_gpxe': 0,
        'fetchable_files': {   },
        'gateway': '10.33.33.1',
        'hostname': 'compute02.rs.zbi.cba',
        'image': '',
        'interfaces': {   'em2': {   'bonding': '',
                                     'bonding_master': '',
                                     'bonding_opts': '',
                                     'bridge_opts': '',
                                     'cnames': [],
                                     'dhcp_tag': '',
                                     'distro': {   'arch': 'x86_64',
                                                   'boot_files': {   },
                                                   'breed': 'ubuntu',
                                                   'comment': '',
                                                   'ctime': 1447693852.378105,
                                                   'depth': 0,
                                                   'fetchable_files': {   },
                                                   'initrd': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/initrd.gz',
                                                   'kernel': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/linux',
                                                   'kernel_options': {   },
                                                   'kernel_options_post': {   },
                                                   'ks_meta': {   'tree': 'http://@@http_server@@/cblr/links/ubuntu-14.04.3-server-x86_64'},
                                                   'mgmt_classes': [],
                                                   'mtime': 1447693853.425006,
                                                   'name': 'ubuntu-14.04.3-server-x86_64',
                                                   'os_version': 'trusty',
                                                   'owners': ['admin'],
                                                   'redhat_management_key': '<<inherit>>',
                                                   'redhat_management_server': '<<inherit>>',
                                                   'source_repos': [],
                                                   'template_files': {   },
                                                   'tree_build_time': 0,
                                                   'uid': 'MTQ0NzY5Mzg1Mi4zODY4NDc3Ny43MTk2NTk'},
                                     'dns_name': '',
                                     'enable_gpxe': 0,
                                     'filename': '/pxelinux.0',
                                     'gateway': '10.33.33.1',
                                     'hostname': 'compute02.rs.zbi.cba',
                                     'if_gateway': '',
                                     'interface_master': '',
                                     'interface_type': '',
                                     'ip_address': '10.33.33.54',
                                     'ipv6_address': '',
                                     'ipv6_default_gateway': '',
                                     'ipv6_mtu': '',
                                     'ipv6_secondaries': [],
                                     'ipv6_static_routes': [],
                                     'mac_address': '0c:c4:7a:c1:2d:17',
                                     'management': False,
                                     'mtu': '',
                                     'name': 'generic5',
                                     'netboot_enabled': True,
                                     'netmask': '255.255.255.0',
                                     'next_server': '10.33.33.2',
                                     'owner': 'compute02.rs.zbi.cba',
                                     'static': False,
                                     'static_routes': [],
                                     'subnet': '',
                                     'virt_bridge': ''}},
        'ipv6_autoconfiguration': False,
        'ipv6_default_device': '',
        'kernel_options': {   'interface': 'em2'},
        'kernel_options_post': {   },
        'kickstart': '<<inherit>>',
        'ks_meta': {   },
        'ldap_enabled': False,
        'ldap_type': 'authconfig',
        'mgmt_classes': [],
        'mgmt_parameters': '<<inherit>>',
        'monit_enabled': False,
        'mtime': 1458535801.276064,
        'name': 'compute02.rs.zbi.cba',
        'name_servers': ['10.33.33.1'],
        'name_servers_search': [],
        'netboot_enabled': False,
        'owners': ['admin'],
        'power_address': '10.44.44.105',
        'power_id': '',
        'power_pass': 'ADMIN',
        'power_type': 'ipmilan',
        'power_user': 'ADMIN',
        'profile': 'ubuntu-14.04.3-server-unattended-rpc',
        'proxy': '<<inherit>>',
        'redhat_management_key': '<<inherit>>',
        'redhat_management_server': '<<inherit>>',
        'repos_enabled': False,
        'server': '<<inherit>>',
        'status': 'production',
        'template_files': {   },
        'template_remote_kickstarts': 0,
        'uid': 'MTQ1ODUzNTIyMS4xNTM5MzQwOTEuNDc3MDM',
        'virt_auto_boot': '<<inherit>>',
        'virt_cpus': '<<inherit>>',
        'virt_disk_driver': '<<inherit>>',
        'virt_file_size': '<<inherit>>',
        'virt_path': '<<inherit>>',
        'virt_pxe_boot': 0,
        'virt_ram': '<<inherit>>',
        'virt_type': '<<inherit>>'},
    {   'boot_files': {   },
        'comment': '',
        'ctime': 1458531425.296812,
        'depth': 2,
        'enable_gpxe': 0,
        'fetchable_files': {   },
        'gateway': '10.33.33.1',
        'hostname': 'compute01.rs.zbi.cba',
        'image': '',
        'interfaces': {   'eth1': {   'bonding': '',
                                      'bonding_master': '',
                                      'bonding_opts': '',
                                      'bridge_opts': '',
                                      'cnames': [],
                                      'dhcp_tag': '',
                                      'distro': {   'arch': 'x86_64',
                                                    'boot_files': {   },
                                                    'breed': 'ubuntu',
                                                    'comment': '',
                                                    'ctime': 1447693852.378105,
                                                    'depth': 0,
                                                    'fetchable_files': {   },
                                                    'initrd': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/initrd.gz',
                                                    'kernel': '/var/www/cobbler/ks_mirror/ubuntu-14.04.3-server-amd64/install/netboot/ubuntu-installer/amd64/linux',
                                                    'kernel_options': {   },
                                                    'kernel_options_post': {   },
                                                    'ks_meta': {   'tree': 'http://@@http_server@@/cblr/links/ubuntu-14.04.3-server-x86_64'},
                                                    'mgmt_classes': [],
                                                    'mtime': 1447693853.425006,
                                                    'name': 'ubuntu-14.04.3-server-x86_64',
                                                    'os_version': 'trusty',
                                                    'owners': ['admin'],
                                                    'redhat_management_key': '<<inherit>>',
                                                    'redhat_management_server': '<<inherit>>',
                                                    'source_repos': [],
                                                    'template_files': {   },
                                                    'tree_build_time': 0,
                                                    'uid': 'MTQ0NzY5Mzg1Mi4zODY4NDc3Ny43MTk2NTk'},
                                      'dns_name': '',
                                      'enable_gpxe': 0,
                                      'filename': '/pxelinux.0',
                                      'gateway': '10.33.33.1',
                                      'hostname': 'compute01.rs.zbi.cba',
                                      'if_gateway': '',
                                      'interface_master': '',
                                      'interface_type': '',
                                      'ip_address': '10.33.33.53',
                                      'ipv6_address': '',
                                      'ipv6_default_gateway': '',
                                      'ipv6_mtu': '',
                                      'ipv6_secondaries': [],
                                      'ipv6_static_routes': [],
                                      'mac_address': 'fc:15:b4:79:77:78',
                                      'management': False,
                                      'mtu': '',
                                      'name': 'generic4',
                                      'netboot_enabled': True,
                                      'netmask': '255.255.255.0',
                                      'next_server': '10.33.33.2',
                                      'owner': 'compute01.rs.zbi.cba',
                                      'static': False,
                                      'static_routes': [],
                                      'subnet': '',
                                      'virt_bridge': ''}},
        'ipv6_autoconfiguration': False,
        'ipv6_default_device': '',
        'kernel_options': {   'interface': 'eth1'},
        'kernel_options_post': {   },
        'kickstart': '<<inherit>>',
        'ks_meta': {   },
        'ldap_enabled': False,
        'ldap_type': 'authconfig',
        'mgmt_classes': [],
        'mgmt_parameters': '<<inherit>>',
        'monit_enabled': False,
        'mtime': 1458531811.539002,
        'name': 'compute01.rs.zbi.cba',
        'name_servers': ['10.33.33.1'],
        'name_servers_search': [],
        'netboot_enabled': False,
        'owners': ['admin'],
        'power_address': '10.44.44.100',
        'power_id': '',
        'power_pass': 'admin',
        'power_type': 'ipmilan',
        'power_user': 'admin',
        'profile': 'ubuntu-14.04.3-server-unattended-rpc',
        'proxy': '<<inherit>>',
        'redhat_management_key': '<<inherit>>',
        'redhat_management_server': '<<inherit>>',
        'repos_enabled': False,
        'server': '<<inherit>>',
        'status': 'production',
        'template_files': {   },
        'template_remote_kickstarts': 0,
        'uid': 'MTQ1ODUzMTQyNS4zNzk2MTM1Mi43NzcwMw',
        'virt_auto_boot': '<<inherit>>',
        'virt_cpus': '<<inherit>>',
        'virt_disk_driver': '<<inherit>>',
        'virt_file_size': '<<inherit>>',
        'virt_path': '<<inherit>>',
        'virt_pxe_boot': 0,
        'virt_ram': '<<inherit>>',
        'virt_type': '<<inherit>>'}]